### ISSUE TITLE
Update K8s deployment in GKE by setting new container image via Cloudify workflow or node template

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-kubernetes-plugin#39]
Take a look at this kubectl command:
kubectl set image deployment/hello-app hello-app=gcr.io/gigaspaces-joshuap/hello-app:v2

If I run this command on GKE after doing a kubectl deployment, then the hello world application is updated in rolling update fashion by using a newly built and updated docker container image house in Google Container Registry.

I am looking to create a workflow/node template or blueprint which updates the docker container image without the need for a full redeployment. Is this supported with the cloudify-kubernetes-plugin?

If so, is there an example blueprint I can look at?

**Comment by EarthmanT** [comment]
Fixed in #71
