### ISSUE TITLE
Delete Resources Issues

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-kubernetes-plugin#45]
Delete Deployment and ReplicaSets is not always successful.

Execute Install workflow to Create Deployment with one of these blueprints:
- https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/blob/master/examples/wordpress-blueprint.yaml
- https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/blob/master/examples/replicasets-blueprint.yaml

Then execute uninstall workflow. Check the Kubernetes Master.
The deployment and replica sets are still running.
We need to figure out what is missing to make these delete.

Related to: https://github.com/cloudify-incubator/cloudify-kubernetes-plugin/issues/40

**Comment by mabuaisha** [comment]
This issue is no longer exists and the fix added
