### ISSUE TITLE
Error in getting pod status in kubernetes get pod status

### ISSUE THREAD

**Issue by smirzai** [cloudify-incubator/cloudify-kubernetes-plugin#77]
There seems to be a problem in tasks.py line 181 where it checks the status of deployed pod.
The current logic checks the conditions in status and iterates them. If there is even one condition with status == "progressing" then an exception is failed and task is considered to be failed and is scheduled for redeploy. This is a never ending loop.
According to the [kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/), a "progressing" status is not sufficient and we also need to check the reason field. If it is "NewReplicaSetAvailable", the condition cannot be considered to be failed.
This can be fixed by adding another condition int he mentioned line in tasks.py.
I am testing against kubernetes v1.10.0
A small fixing pull request will follow.

**Comment by EarthmanT** [comment]
#78 #79
